version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      security-patches:
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-patches:
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
