  #!/bin/bash                                                                                                                                                                                                                                  
  # ui/scripts/prisma-migrate.sh                                                                                                                                                                                                               
                                                                                                                                                                                                                                               
  set -e                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                               
  cd "$(dirname "$0")/.."                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
  MIGRATION_NAME="migration_$(date +%Y%m%d%H%M%S)"                                                                                                                                                                                             
  MIGRATION_FILE="prisma/migrations/${MIGRATION_NAME}.sql"                                                                                                                                                                                     
                                                                                                                                                                                                                                               
  echo "Creating migration: $MIGRATION_NAME"                                                                                                                                                                                                   
                                                                                                                                                                                                                                               
  # 1. Generate SQL diff (no drift check, no history)                                                                                                                                                                                          
  npx prisma migrate diff --from-schema-datasource prisma/schema.prisma --to-schema-datamodel prisma/schema.prisma --script > "$MIGRATION_FILE"                                                                                                
                                                                                                                                                                                                                                               
  if [ ! -s "$MIGRATION_FILE" ]; then                                                                                                                                                                                                          
      echo "No changes detected"                                                                                                                                                                                                               
      rm -f "$MIGRATION_FILE"                                                                                                                                                                                                                  
      exit 0                                                                                                                                                                                                                                   
  fi                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                               
  # 2. Extract table names from schema.prisma                                                                                                                                                                                                  
  SCHEMA_TABLES=$(grep -o '@@map("[^"]*")' prisma/schema.prisma | sed 's/@@map("//g; s/")//g')                                                                                                                                                 
                                                                                                                                                                                                                                               
  # 3. Remove DROP TABLE for tables not in schema                                                                                                                                                                                              
  while IFS= read -r line; do                                                                                                                                                                                                                  
      if echo "$line" | grep -q "DROP TABLE"; then                                                                                                                                                                                             
          table_name=$(echo "$line" | grep -o '"[^"]*"' | tr -d '"')                                                                                                                                                                           
          if echo "$SCHEMA_TABLES" | grep -q "^${table_name}$"; then                                                                                                                                                                           
              echo "$line"                                                                                                                                                                                                                     
          else                                                                                                                                                                                                                                 
              echo "-- REMOVED: $line" >&2                                                                                                                                                                                                     
          fi                                                                                                                                                                                                                                   
      else                                                                                                                                                                                                                                     
          echo "$line"                                                                                                                                                                                                                         
      fi                                                                                                                                                                                                                                       
  done < "$MIGRATION_FILE" > "${MIGRATION_FILE}.tmp"                                                                                                                                                                                           
                                                                                                                                                                                                                                               
  mv "${MIGRATION_FILE}.tmp" "$MIGRATION_FILE"                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
  echo ""                                                                                                                                                                                                                                      
  echo "Migration file:"                                                                                                                                                                                                                       
  echo "==============="                                                                                                                                                                                                                       
  cat "$MIGRATION_FILE"                                                                                                                                                                                                                        
  echo "==============="                                                                                                                                                                                                                       
                                                                                                                                                                                                                                               
  # 4. Execute directly                                                                                                                                                                                                                        
  read -p "Apply this migration ./$MIGRATION_FILE to the database? (y/n) " -n 1 -r                                                                                                                                                                                               
  echo                                                                                                                                                                                                                                         
  if [[ $REPLY =~ ^[Yy]$ ]]; then                                                                                                                                                                                                              
      npx prisma db execute --file "$MIGRATION_FILE"                                                                                                                                                                                           
      npx prisma generate                                                                                                                                                                                                                      
      echo "Migration applied!"                                                                                                                                                                                                                
  else                                                                                                                                                                                                                                         
      echo "Migration saved at: $MIGRATION_FILE"                                                                                                                                                                                               
  fi                                                            