"use client";                                                                                                                                                                                                                          
                                                                                                                                                                                                                                         
  import { useEffect } from "react";                                                                                                                                                                                                     
  import { useRouter } from "next/navigation";                                                                                                                                                                                           
  import { useSession } from "next-auth/react";                                                                                                                                                                                          
  import { useQuery } from "@tanstack/react-query";                                                                                                                                                                                      
  import { getOrganizations } from "@/lib/api";                                                                                                                                                                                          
  import {                                                                                                                                                                                                                               
    Card,                                                                                                                                                                                                                                
    CardContent,                                                                                                                                                                                                                         
    CardDescription,                                                                                                                                                                                                                     
    CardHeader,                                                                                                                                                                                                                          
    CardTitle,                                                                                                                                                                                                                           
  } from "@/components/ui/card";                                                                                                                                                                                                         
  import { CreateOrgDialog } from "@/components/CreateOrgDialog";                                                                                                                                                                        
                                                                                                                                                                                                                                         
  export default function Home() {                                                                                                                                                                                                       
    const router = useRouter();                                                                                                                                                                                                          
    const { data: session, status } = useSession();                                                                                                                                                                                      
                                                                                                                                                                                                                                         
    const { data: organizations, isLoading: orgsLoading } = useQuery({                                                                                                                                                                   
      queryKey: ["organizations"],                                                                                                                                                                                                       
      queryFn: getOrganizations,                                                                                                                                                                                                         
      enabled: status === "authenticated",                                                                                                                                                                                               
    });                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                         
    useEffect(() => {                                                                                                                                                                                                                    
      if (organizations && organizations.length > 0) {                                                                                                                                                                                   
        router.push("/organizations");                                                                                                                                                                                                   
      }                                                                                                                                                                                                                                  
    }, [organizations, router]);                                                                                                                                                                                                         
                                                                                                                                                                                                                                         
    if (status === "loading") {                                                                                                                                                                                                          
      return (                                                                                                                                                                                                                           
        <div className="flex min-h-screen items-center justify-center">                                                                                                                                                                  
          <p className="text-muted-foreground">Loading...</p>                                                                                                                                                                            
        </div>                                                                                                                                                                                                                           
      );                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                         
    if (status === "unauthenticated") {                                                                                                                                                                                                  
      router.push("/auth/sign-in");                                                                                                                                                                                                      
      return (                                                                                                                                                                                                                           
        <div className="flex min-h-screen items-center justify-center">                                                                                                                                                                  
          <p className="text-muted-foreground">Redirecting to sign in...</p>                                                                                                                                                             
        </div>                                                                                                                                                                                                                           
      );                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                         
    if (orgsLoading) {                                                                                                                                                                                                                   
      return (                                                                                                                                                                                                                           
        <div className="flex min-h-screen items-center justify-center">                                                                                                                                                                  
          <p className="text-muted-foreground">Loading organizations...</p>                                                                                                                                                              
        </div>                                                                                                                                                                                                                           
      );                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                         
    return (                                                                                                                                                                                                                             
      <div className="flex min-h-screen items-center justify-center p-4">                                                                                                                                                                
        <Card className="w-full max-w-md">                                                                                                                                                                                               
          <CardHeader className="text-center">                                                                                                                                                                                           
            <CardTitle className="text-2xl">                                                                                                                                                                                             
              Welcome, {session?.user?.name || session?.user?.email}!                                                                                                                                                                    
            </CardTitle>                                                                                                                                                                                                                 
            <CardDescription>                                                                                                                                                                                                            
              Create your first organization to get started.                                                                                                                                                                             
            </CardDescription>                                                                                                                                                                                                           
          </CardHeader>                                                                                                                                                                                                                  
          <CardContent className="flex justify-center">                                                                                                                                                                                  
            <CreateOrgDialog />                                                                                                                                                                                                          
          </CardContent>                                                                                                                                                                                                                 
        </Card>                                                                                                                                                                                                                          
      </div>                                                                                                                                                                                                                             
    );        
  }                                                         