name: Test

"on":
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[all]"

      - name: Run tests
        run: |
          pytest test
